---
title: "Estimation File"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# regress quality on each of the 3 admetrics 
lm1 <- lm(qua~nat+loc+dig+
     lag1nat+lag2nat+lag3nat+lag4nat+lag5nat+
     lag1loc+lag2loc+lag3loc+lag4loc+lag5loc+
     lag1dig+lag2dig+lag3dig+lag4dig+lag5dig+
     compnat+comploc+compdig+
     lag1compnat+lag2compnat+lag3compnat+lag4compnat+lag5compnat+
     lag1comploc+lag2comploc+lag3comploc+lag4comploc+lag5comploc+
     lag1compdig+lag2compdig+lag3compdig+lag4compdig+lag5compdig+
     lag1qua+lag2qua+lag3qua+lag4qua+lag5qua+lag6qua+lag7qua+lag8qua+lag9qua+lag10qua+lag11qua+lag12qua+lag13qua+
     lag1val+lag2val+lag3val+lag4val+lag5val+lag6val+lag7val+lag8val+lag9val+lag10val+lag11val+lag12val+lag13val+
     lag1sat+lag2sat+lag3sat+lag4sat+lag5sat+lag6sat+lag7sat+lag8sat+lag9sat+lag10sat+lag11sat+lag12sat+lag13sat+
     as.factor(Brand) + as.factor(time_period), data=dat5)
```

```{r}
# install lfe package for felm
install.packages('lfe')
library(lfe)
```

```{r}
# use the felm command from the lfe package
fm1 <- felm(qua~nat+loc+dig+
     lag1nat+lag2nat+lag3nat+lag4nat+lag5nat+
     lag1loc+lag2loc+lag3loc+lag4loc+lag5loc+
     lag1dig+lag2dig+lag3dig+lag4dig+lag5dig+
     compnat+comploc+compdig+
     lag1compnat+lag2compnat+lag3compnat+lag4compnat+lag5compnat+
     lag1comploc+lag2comploc+lag3comploc+lag4comploc+lag5comploc+
     lag1compdig+lag2compdig+lag3compdig+lag4compdig+lag5compdig+
     lag1qua+lag2qua+lag3qua+lag4qua+lag5qua+lag6qua+lag7qua+lag8qua+lag9qua+lag10qua+lag11qua+lag12qua+lag13qua+
     lag1val+lag2val+lag3val+lag4val+lag5val+lag6val+lag7val+lag8val+lag9val+lag10val+lag11val+lag12val+lag13val+
     lag1sat+lag2sat+lag3sat+lag4sat+lag5sat+lag6sat+lag7sat+lag8sat+lag9sat+lag10sat+lag11sat+lag12sat+lag13sat|
     as.factor(Brand) + as.factor(time_period), data=dat5)
```

```{r}
# weight the data by qua_vol
fm2 <- felm(qua~nat+loc+dig+
     lag1nat+lag2nat+lag3nat+lag4nat+lag5nat+
     lag1loc+lag2loc+lag3loc+lag4loc+lag5loc+
     lag1dig+lag2dig+lag3dig+lag4dig+lag5dig+
     compnat+comploc+compdig+
     lag1compnat+lag2compnat+lag3compnat+lag4compnat+lag5compnat+
     lag1comploc+lag2comploc+lag3comploc+lag4comploc+lag5comploc+
     lag1compdig+lag2compdig+lag3compdig+lag4compdig+lag5compdig+
     lag1qua+lag2qua+lag3qua+lag4qua+lag5qua+lag6qua+lag7qua+lag8qua+lag9qua+lag10qua+lag11qua+lag12qua+lag13qua+
     lag1val+lag2val+lag3val+lag4val+lag5val+lag6val+lag7val+lag8val+lag9val+lag10val+lag11val+lag12val+lag13val+
     lag1sat+lag2sat+lag3sat+lag4sat+lag5sat+lag6sat+lag7sat+lag8sat+lag9sat+lag10sat+lag11sat+lag12sat+lag13sat|
     as.factor(Brand) + as.factor(time_period), data=dat5, weights = fm1$qua_vol)
```

```{r}
# replace the brand fixed effects with brand-quarter fixed effects 
fm3 <- felm(qua~nat+loc+dig+
     lag1nat+lag2nat+lag3nat+lag4nat+lag5nat+
     lag1loc+lag2loc+lag3loc+lag4loc+lag5loc+
     lag1dig+lag2dig+lag3dig+lag4dig+lag5dig+
     compnat+comploc+compdig+
     lag1compnat+lag2compnat+lag3compnat+lag4compnat+lag5compnat+
     lag1comploc+lag2comploc+lag3comploc+lag4comploc+lag5comploc+
     lag1compdig+lag2compdig+lag3compdig+lag4compdig+lag5compdig+
     lag1qua+lag2qua+lag3qua+lag4qua+lag5qua+lag6qua+lag7qua+lag8qua+lag9qua+lag10qua+lag11qua+lag12qua+lag13qua+
     lag1val+lag2val+lag3val+lag4val+lag5val+lag6val+lag7val+lag8val+lag9val+lag10val+lag11val+lag12val+lag13val+
     lag1sat+lag2sat+lag3sat+lag4sat+lag5sat+lag6sat+lag7sat+lag8sat+lag9sat+lag10sat+lag11sat+lag12sat+lag13sat|
     as.factor(Brand)*as.factor(yrqtr) + as.factor(time_period), data=dat5, weights = fm2$qua_vol)
```

```{r}
# replace the week fixed effects with industry-week fixed effects
fm4 <- felm(qua~nat+loc+dig+
     lag1nat+lag2nat+lag3nat+lag4nat+lag5nat+
     lag1loc+lag2loc+lag3loc+lag4loc+lag5loc+
     lag1dig+lag2dig+lag3dig+lag4dig+lag5dig+
     compnat+comploc+compdig+
     lag1compnat+lag2compnat+lag3compnat+lag4compnat+lag5compnat+
     lag1comploc+lag2comploc+lag3comploc+lag4comploc+lag5comploc+
     lag1compdig+lag2compdig+lag3compdig+lag4compdig+lag5compdig+
     lag1qua+lag2qua+lag3qua+lag4qua+lag5qua+lag6qua+lag7qua+lag8qua+lag9qua+lag10qua+lag11qua+lag12qua+lag13qua+
     lag1val+lag2val+lag3val+lag4val+lag5val+lag6val+lag7val+lag8val+lag9val+lag10val+lag11val+lag12val+lag13val+
     lag1sat+lag2sat+lag3sat+lag4sat+lag5sat+lag6sat+lag7sat+lag8sat+lag9sat+lag10sat+lag11sat+lag12sat+lag13sat|
     as.factor(Brand)*as.factor(yrqtr) + as.factor(time_period)*as.factor(Industry), data=dat5, weights = fm3$qua_vol)
```

```{r}
install.packages("stargazer")
library(stargazer)
```

```{r}
# create a pretty table 
stargazer(fm1, fm2, fm3, fm4, title="Regression Results", type='text', format = 'e', digits = 2, align = TRUE, omit = c('lag1qua', 'lag2qua', 'lag3qua', 'lag4qua', 'lag5qua', 'lag6qua', 'lag7qua', 'lag8qua', 'lag9qua', 'lag10qua', 'lag11qua', 'lag12qua', 'lag13qua',
     'lag1val', 'lag2val', 'lag3val', 'lag4val', 'lag5val', 'lag6val', 'lag7val', 'lag8val', 'lag9val', 'lag10val', 'lag11val', 'lag12val', 'lag13val',
     'lag1sat', 'lag2sat', 'lag3sat', 'lag4sat', 'lag5sat', 'lag6sat', 'lag7sat', 'lag8sat', 'lag9sat', 'lag10sat', 'lag11sat', 'lag12sat', 'lag13sat'), column.labels = c('Felm Regression', 'Weighted Regression', 'Brand-Quarter', 'Indsutry-Week'), column.sep.width = '8pt')
```

```{r}
#install.packages('tinytex')
```

```{r, include=FALSE}
#options(tinytex.verbose = TRUE)
```
